# TurtleBot3 + SLAM (narrow passage friendly) / ROS 2 Humble

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    controller_plugins:
      - FollowPath
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.10
      movement_time_allowance: 3.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.02
      yaw_goal_tolerance: 0.35
      stateful: true
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      transform_tolerance: 0.2
      desired_linear_vel: 0.18
      min_approach_linear_velocity: 0.0
      lookahead_dist: 0.20
      min_lookahead_dist: 0.12
      max_lookahead_dist: 0.26
      use_velocity_scaled_lookahead_dist: false
      allow_reversing: true
      allow_rotate_in_place: true

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins:
      - GridBased
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"   # <-- 여기 고침 (:: -> /)
      use_astar: true
      tolerance: 0.10
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins:
      - simple_smoother
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      w_data: 0.2
      w_smooth: 0.3

behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins:
      - spin
      - backup
      - drive_on_heading
      - wait
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      waypoint_pause_duration: 1

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: true
    odom_topic: /odom
    odom_duration: 0.1
    max_velocity: [0.18, 0.0, 0.80]
    max_accel:    [1.0,  0.0, 2.0]
    max_decel:    [-1.0,  0.0, -2.0]

# ===== Global Costmap =====
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.01
      track_unknown_space: true
      always_send_full_costmap: true
      robot_radius: 0.11
      footprint_padding: 0.04
      plugins:
        - static_layer
        - inflation_layer
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        subscribe_to_updates: true
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.15
        cost_scaling_factor: 8.0

# ===== Local Costmap =====
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.01  
      robot_radius: 0.11
      footprint_padding: 0.01
      plugins:
        - obstacle_layer
        - inflation_layer
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          max_obstacle_height: 0.30
          obstacle_range: 3.0
          raytrace_range: 3.5
          clearing: true
          marking: true
          inf_is_valid: false
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.15
        cost_scaling_factor: 2.5

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - controller_server
      - planner_server
      - smoother_server
      - behavior_server
      - bt_navigator
      - waypoint_follower
      - velocity_smoother
